version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./storage:/app/storage
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=polydrive
      - DATABASE_PASSWORD=polydrive123
      - DATABASE_NAME=polydrive
      - JWT_SECRET=your-secret-key-change-in-production
      - STORAGE_TYPE=s3
      - LOCAL_STORAGE_PATH=/app/storage
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_BUCKET=polydrive
      - S3_REGION=us-east-1
      - FTP_HOST=ftp
      - FTP_USER=ftpuser
      - FTP_PASSWORD=ftppass
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
      ftp:
        condition: service_started
    command: npm run start:dev

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=polydrive
      - POSTGRES_PASSWORD=polydrive123
      - POSTGRES_DB=polydrive
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U polydrive -d polydrive"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  ftp:
    image: stilliard/pure-ftpd:latest
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      - PUBLICHOST=localhost
      - FTP_USER_NAME=ftpuser
      - FTP_USER_PASS=ftppass
      - FTP_USER_HOME=/home/ftpuser
    volumes:
      - ftp_data:/home/ftpuser

volumes:
  postgres_data:
  minio_data:
  ftp_data: 